version: "3.8"

services:
  api-tdl-app:
    image: joshbuker/api-tdl-app:latest
    depends_on:
      - api-tdl-app-postgres-db
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
  api-tdl-app-postgres-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: api_tdl_app
      POSTGRES_PASSWORD: ${API_TDL_APP_DATABASE_PASSWORD:?Please configure API_TDL_APP_DATABASE_PASSWORD}
      POSTGRES_DB: api_tdl_app_production

volumes:
  postgres-data: {}
